language: go

go:
  - "1.11.x"
  - master

before_script:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep ensure

script:
  - go test -v ./...

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file_glob: true
  file: terraform-provider-zendesk-*.tar.gz
  skip_cleanup: true
  on:
    tags: true
