language: go

go:
  - "1.11.x"
  - "1.12.x"
  - master

env:
  - GO111MODULE=on

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

before_install:
  - go get github.com/mattn/goveralls # for profiling coverage

install:
  - go mod download

script:
  - go test -v ./...
  - goveralls -service=travis-ci

before_deploy:
  - go get github.com/mitchellh/gox
  - gox -os="linux darwin windows" -arch="386 amd64" -output="{{.Dir}}-{{.OS}}-{{.Arch}}/{{.Dir}}"
  - |
      for os in linux darwin windows; do
        for arch in 386 amd64; do
          cp README.md LICENSE terraform-provider-zendesk-$os-$arch
          zip -r terraform-provider-zendesk-$os-$arch.zip terraform-provider-zendesk-$os-$arch
        done
      done

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: terraform-provider-zendesk-*-*.zip
  skip_cleanup: true
  on:
    tags: true
    go: "1.11.x"

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4ee2368b1378e7ade98d
    on_success: change
    on_failure: always
    on_start: never
